config/routes.rb
Spree::Core::Engine.routes.draw do
  resources :contacts, :controller => 'contact_us/contacts', :only => [:new, :create]
  get 'contact-us' => 'contact_us/contacts#new', :as => :contact_us
end

app/models/spree/contact_us/contact.rb
module Spree
  module ContactUs
    class Contact
      # enum contact_type: [:contact_normal, :contact_business, :contact_corporate]
      include ActiveModel::Conversion
      include ActiveModel::Validations

      attr_accessor :email, :message, :name, :subject, :phone, :contact_type, :company_name, :web_site, :billing_address, :shipping_address, :interested_products, :reason

      EMAIL_REGEX = /\A
        [^\s@]+ # non-at-sign characters, at least one
          @     # at-sign
        [^\s.@] # non-at-sign and non-period character
        [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
         \.     # period
        [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
        [^\s.@] # non-at-sign and non-period character
      \z/x

      validates :email,   :format => { :with => EMAIL_REGEX },
                          :presence => true
      validates :message, :presence => true
      validates :name,    :presence => {:if => Proc.new{SolidusContactUs.require_name}}
      validates :subject, :presence => {:if => Proc.new{SolidusContactUs.require_subject}}

      def initialize(attributes = {})
        [:email, :message, :name, :subject, :phone, :contact_type, :company_name, :web_site, :billing_address, :shipping_address, :interested_products, :reason].each do |attribute|
          self.send("#{attribute}=", attributes[attribute]) if attributes and attributes.has_key?(attribute)
        end
      end

      def save
        if self.valid?
          Spree::ContactUs::ContactMailer.contact_email(self).deliver
          return true
        end
        return false
      end

      def persisted?
        false
      end

    end
  end
end

app/controllers/spree/contact_us/contacts_controller.rb
class Spree::ContactUs::ContactsController < Spree::StoreController

  helper "spree/products"
  def create
    puts "ContactUs => " + "create"
    @contact = Spree::ContactUs::Contact.new(params[:contact_us_contact])
    status = verify_recaptcha(:model => @post, :message => "Oh! It's error with reCAPTCHA!")
    if status && @contact.save
      if Spree::ContactUs::Config.contact_tracking_message.present?
        flash[:contact_tracking] = Spree::ContactUs::Config.contact_tracking_message
      end
      redirect_to(spree.root_path, :notice => Spree.t('contact_us.notices.success'))
    else
      render :new
    end
  end

  def new
    # puts "ContactUs => " + "new => " + params[:contact_type]
    _type_contact = :type_normal
    if params[:contact_type].present?
      _type_contact = params[:contact_type]
    end
    @contact = Spree::ContactUs::Contact.new
    @contact.contact_type = _type_contact
    @taxonomies = Spree::Taxonomy.includes(root: :children)
  end

  private

  def accurate_title
    Spree.t(:contact_us_title)
  end

end

app/views/spree/contact_us/contacts/new.html.erb
<% content_for :head do -%>
  <meta name="title" content="<%= Spree.t(:contact_us_title) %>">
<% end -%>

<% content_for :sidebar do 
   if "products" == @current_controller && @taxon %>
    <%= render :partial => "spree/shared/filters" %>
  <% else %>
    <%= render :partial => "spree/shared/taxonomies" %>
  <% end
 end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @contact } %>

<h1><%= Spree.t(:contact_us_title) %></h1>
<%= form_for @contact, :url => contacts_path, :html => { :novalidate => '' } do |f| %>
  <% if SolidusContactUs.require_name %>
    <p>
      <%= f.label :name %>
      <span class="required">*</span><br/>
      <%= f.text_field :name, class: 'required' %>
    </p>
  <% end %>
  <p>
    <%= f.label :email %>
    <span class="required">*</span><br/>
    <%= f.email_field :email, class: 'required email' %>
  </p>
  <% if SolidusContactUs.require_subject %>
    <p>
      <%= f.label :subject %>
      <span class="required">*</span><br/>
      <%= f.text_field :subject, class: 'required' %>
    </p>
  <% end %>
  <p>
    <%= f.label :message %>
    <span class="required">*</span><br/>
    <%= f.text_area :message, class: 'required' %>
  </p>
  <p>
    <%= f.submit Spree.t(:submit), :alt => Spree.t(:submit), :id => 'contact_us_contact_submit', :title => Spree.t(:submit) %>
  </p>
<% end %>

app/views/spree/shared/_contact_us.html.erb
<div class="row">
  <div class="col-md-12">
    <div id="map-outer" class="col-md-12">
      <div id="address" class="col-md-4">
            <%= render_snippet('/company-contact-us') %>
      </div>
      <div id="map-container" class="col-md-8">
            <%= render_snippet('/map-contact-us') %>
        </div>
    </div><!-- /map-outer -->
  </div>
</div> <!-- /row -->

<div class="row">

  <%= form_for @contact, :url => contacts_path, :html => { :novalidate => '', :class => 'form-horizontal'} do |f| %>
      <div class="col-md-12" id="name_email">
        <div class="col-md-4 input-group" id="name">
          <span class="input-group-addon" >
            <i class="fa fa-user" aria-hidden="true"></i>
          </span>
          <%= f.text_field :name, class: 'form-control required',:id =>  "name", :placeholder => Spree.t(:name)  %>
        </div>
        <div class="col-md-4  input-group" id="email">
          <span class="input-group-addon">
            <i class="fa fa-envelope" aria-hidden="true"></i>
          </span>
          <%= f.email_field :email, class: 'form-control required', :id => "email", :placeholder => t(:email_address) %>
        </div>
        <div class="col-md-4 input-group" id="phone">
          <span class="input-group-addon">
            <i class="fa fa-phone" aria-hidden="true"></i>
          </span>
          <%= f.text_field :phone, class: 'form-control',:id =>  "phone", :placeholder => Spree.t(:phone)  %>
        </div>
      </div>
      <div class="col-md-12 col-xs-12" id="comments">
        <div class="col-md-12 input-group">
              <span class="input-group-addon">
                <i class="fa fa-pencil"></i>
              </span>
          <%= f.text_area :message, class: 'form-control required', :rows => "6", :id => "comments_area", :placeholder => t(:your_comment_here) %>
        </div>
      </div>
      <div class="col-md-12 col-xs-12">
				<%= recaptcha_tags({hl:I18n.locale}) %>
      </div>
      <div class="col-md-12 col-xs-12">
        <div class="col-md-12 input-group">
          <label class="checkbox required micro" id="label_contact_term_and_cond" for="contact_term_and_cond" required>
            <input type="checkbox" id="contact_term_and_cond" name="contact[term_and_cond]" required="required" value="1" />
            <%= t(:contact_term_and_cond) %>
          </label>
        </div>
      </div>
      <div class="col-md-12 col-xs-12">
        <%= f.submit Spree.t(:submit), :alt => Spree.t(:submit), :class => 'btn btn-primary btn-lg', :id => 'contact_us_contact_submit', :title => Spree.t(:submit) %>
      </div>
  <% end %>
  <% if I18n.locale != :en %>
      <% content_for :head do %>
          <script src="<%= assets_prefix %>/jquery.validate/localization/messages_<%= I18n.locale.to_s.downcase.gsub("-", "") %>.js"></script>
      <% end %>
  <% end %>  
</div>